# Generated by Django 4.0.6 on 2022-07-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_blogpost_chead0_remove_blogpost_chead1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='preContent',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
