# Generated by Django 3.2 on 2022-07-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogpost_precontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_IP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userIP', models.TextField(default=None)),
                ('slug', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
