# Generated by Django 3.2 on 2022-07-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20220728_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='PostViews',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='poster',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='preContent',
            field=models.TextField(),
        ),
    ]
