# Generated by Django 3.2 on 2022-07-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20220728_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='tag',
            field=models.TextField(default='post'),
        ),
    ]
