# Generated by Django 4.0.6 on 2022-08-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_blogpost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('you-will-love-to-know', 'You will love to know'), ('superhero', 'SuperHero'), ('hollywood', 'Hollywood'), ('bollywood', 'Bollywood'), ('anime', 'Anime')], default='you_will_love_to_know', max_length=60),
        ),
    ]
