# Generated by Django 4.0.6 on 2022-08-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_blogpost_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('name', models.CharField(default='', max_length=300)),
                ('preContent', models.TextField()),
                ('playlist', models.BooleanField(default=True)),
                ('thumbnail', models.ImageField(default='', upload_to='shop/playlistImages')),
            ],
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='updated',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='PlaylistName',
            field=models.CharField(default='', max_length=300),
        ),
    ]
