# Generated by Django 4.0.6 on 2022-08-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_playlist_remove_blogpost_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='PlaylistName',
            field=models.CharField(default='none', max_length=300),
        ),
    ]
