# Generated by Django 4.0.6 on 2022-08-11 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_notification_image_push_token_countrylist_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='notification_image',
        ),
        migrations.DeleteModel(
            name='push_token_countryList',
        ),
        migrations.DeleteModel(
            name='user_push_token',
        ),
    ]
