# Generated by Django 4.0.6 on 2022-08-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_notification_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_tokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=1000, unique=True)),
            ],
        ),
    ]
